### ISSUE TITLE
Starting client error

### ISSUE THREAD

**Issue by y0d4a** [loseys/Oblivion#1]
Hi, i installed all modules which he required and when i try to start OblivionClient i get this error:
```
# python3 OblivionClient.py
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```
PyQt5 is installed

**Comment by loseys** [comment]
> Hi, i installed all modules which he required and when i try to start OblivionClient i get this error:
> 
> ```
> # python3 OblivionClient.py
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
> 
> Aborted (core dumped)
> ```
> 
> PyQt5 is installed

Hello, can you send me please your python version and OS name/version?

**Comment by y0d4a** [comment]
hi, i have python2.7 and 3.6
CentOS Linux release 7.9.2009 (Core)

tnx

**Comment by loseys** [comment]
Hello, y0d4a. Currently the CentOS Linux is not compatible with the Oblivion.

It's recomended that you use the Windows 10 for graphical use or Ubuntu 20.04 for the server use. By the way you can try another OS, but is not guarented the instabilitie or correctly functionalite and  make sure that you are using the Python 3.8.

For more informations please read the documentation.

**Comment by y0d4a** [comment]
thank you

**Comment by y0d4a** [comment]
hi, i just setup it on latest ubuntu.
But when i try to start client he breaks:
`$ sudo python3.8 OblivionClient.py 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted
`

**Comment by loseys** [comment]
Hello, y0d4a!

For your can use the Client mode (GUI) you will need to work with Windows 10. The Client mode is not compatible with GNU/Linux.

If you want to use the Oblivion with Linux you'll need to use the Server mode. The Ubuntu Server is focused unique to Oblivion Server hosting.
